export const LOG_IN = 'LOG_IN';
export const EDIT_PROFILE_NAME = 'EDIT_PROFILE_NAME';
export const EDIT_PROFILE_PICTURE = 'EDIT_PROFILE_PICTURE';
export const DISPLAY_MATCHES = 'DISPLAY_MATCHES';
export const DISPLAY_LIKES = 'DISPLAY_LIKES';
export const DISPLAY_EXPLORE = 'DISPLAY_EXPLORE';
